---
#Ensure this runs on dns_server
- hosts:
        dns_server

#Initiallize necessary parameters
- vars:
        domain_name=
        domain_admin_pasword=

#Task to execute
- name: Install AD Domain Services
  win_feature:
        name: Active Directory Domain Services
	state: present
  register: win_feature_result

#Cant push this to hadler as this is madatory
#Reboot the server afterabove is installed
- name: rebooting after installing AD Directory services feature
  win_reboot:
        when: win_feature_result.reboot_required

